version: '2'
services:
    truequek-app:
        image: truequek
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://truequek-postgresql:5432/truequek
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://truequek-elasticsearch:9200
        ports:
            - 8080:8080
    truequek-postgresql:
        extends:
            file: postgresql.yml
            service: truequek-postgresql
    truequek-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: truequek-elasticsearch
